[workspace]
members = [
    "lib/procs",
    "lib/core",
]

[package]
name = "distributed-systems-assignment"
version = "0.1.0"
edition = "2021"

[lib]
name = "cs4545"
path = "src/lib.rs"

[dependencies]
procs = { path = "lib/procs" }
framework = { path = "lib/core" }
serde = "1.0.228"
serde_json = "1.0.145"
typetag = "0.2.21"

[dev-dependencies]
tokio-test = "0.4"
