# Configuration for Echo algorithm with 3 nodes

n1:
  neighbours: [] # Empty list means fully connected
  start_node: true

n2:
  neighbours: []
  start_node: false

n3:
  neighbours: []
  start_node: false
