# Shared template for dummy config (upper + lower layer)
# Note: The template key starts with _ to indicate it's not a node
_defaults: &defaults
  start_node: false
  broadcast:
    is_sender: false

node1:
  <<: *defaults
  neighbours:
    - node2
    - node3
  start_node: true

node2:
  <<: *defaults
  neighbours:
    - node1
    - node3

node3:
  <<: *defaults
  neighbours:
    - node1
    - node2
