node1:
  neighbours:
    - node2
    - node3
  start_node: true
  dummy_config: "node1_custom_value"
  broadcast:
    dummy_config: "node1_lower_layer"

node2:
  neighbours:
    - node1
    - node3
  start_node: false
  dummy_config: "node2_custom_value"
  broadcast:
    dummy_config: "node2_lower_layer"

node3:
  neighbours:
    - node1
    - node2
  start_node: false
  dummy_config: "node3_custom_value"
  broadcast:
    dummy_config: "node3_lower_layer"
